#!/usr/bin/env python

import subprocess
import argparse
import os
import sys
import tempfile
import stat
import shutil
import glob
from sipyco import pyon
from setups import *
from templates import device_db_template, scope_template


# =================================================================================================
# Prepare mapping and constants
# =================================================================================================

serial_mapping = {}

for system, ftdi_path in ftdi_mapping.items():
    if ftdi_path is None:
        serial_mapping[system] = "/dev/serial/by-id/usb-FTDI_Quad_RS232-HS-if02-port0"
        continue
    _, path = ftdi_path.split(':')
    path = path.replace(',', '.')
    serial_mapping[system] = f"/dev/serial/by-path/pci-0000:00:14.0-usb-0:{path}:1.2-port0"

experiments_path = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), 'experiments')
default_firmware_directory = os.path.join(
    os.path.dirname(os.path.realpath(__file__)), 'firmware', 'qce24')

# =================================================================================================
# Argument parsing
# =================================================================================================

parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest='command')

# =================================================================================================

flash_parser = subparsers.add_parser('flash')
flash_parser.add_argument('--directory', '-d', type=str, default=default_firmware_directory, 
                          help="firmware directory")
flash_parser.add_argument('--system', '-s', type=str, required=True, 
                          help="which system to flash (A or B or .. F or X or 'all' for all)")

# =================================================================================================

restart_parser = subparsers.add_parser('restart')
restart_parser.add_argument('--system', '-s', type=str, required=True, 
                            help="which system to restart (A or B or .. F or X or 'all' for all)")

# =================================================================================================

serial_parser = subparsers.add_parser('serial')
serial_parser.add_argument('--system', '-s', type=str, required=True, 
                           help="which system to get serial from (A or B or .. F or X)")

# =================================================================================================

device_db_parser = subparsers.add_parser('ddb')
device_db_parser.add_argument('--system', '-s', type=str, required=True, 
                              help="which system to restart (A .. F or X or 'all' for all)")
device_db_parser.add_argument('--ctl-host', type=str, default="::1", required=False, 
                              help="Oscilloscope controller host")

# =================================================================================================

session_parser = subparsers.add_parser('session')
session_parser.add_argument('--system', '-s', type=str, required=True, 
                            help="which system to get serial from (A or B or .. F)")
session_parser.add_argument('--master-ip', type=str, default="::1", required=False, 
                            help="Master IP address")

# =================================================================================================

update_scripts_parser = subparsers.add_parser('update-scripts')
update_scripts_parser.add_argument('--output', default="./scripts",
                                   help="Scripts output path")
update_scripts_parser.add_argument('--system', '-s', type=str, required=True, 
                                   help="which system to restart (A .. F or X or 'all' for all)")
update_scripts_parser.add_argument('--master-ip', type=str, default="::1", required=False, 
                                   help="Master IP address")
update_scripts_parser.add_argument('--target-dir', required=True, 
                                   help="Target directory where deployment was made")

# =================================================================================================

dashboard_parser = subparsers.add_parser('dashboard')
dashboard_parser.add_argument('--system', '-s', type=str, required=True,
                              help="which system to get serial from (A or B or .. F)")
dashboard_parser.add_argument('--master-ip', type=str, default="::1", required=False, 
                              help="Master IP address")

# =================================================================================================

deploy_parser = subparsers.add_parser('deploy')
deploy_parser.add_argument('--system', '-s', type=str, required=True,
                              help="Create files for given system (A..F or all)")
deploy_parser.add_argument('--target-dir', required=True, 
                           help="Target directory to deploy the scripts")
deploy_parser.add_argument('--users', default=1, type=int, 
                           help="Number of users per setup")
deploy_parser.add_argument('--overwrite-system', action='store_true', 
                           help="Overwrite files in the target directory for given system(s)")
deploy_parser.add_argument('--user', type=str, 
                           help="Recreate directory for given user, to be used with --system")
deploy_parser.add_argument('--overwrite-user', action='store_true', 
                           help="Overwrite files in the target directory for system/user pair")

# =================================================================================================

generate_dashboard_config = subparsers.add_parser('generate-dashboard-config')
generate_dashboard_config.add_argument('--applet-path', type=str, required=True,
                                       help="File path to show_image.py applet with respect to "
                                            "the dashboard host filesystem")
generate_dashboard_config.add_argument('--system', '-s', type=str, required=True,
                                       help="Create files for given system (A..F or all)")
generate_dashboard_config.add_argument('--users', default=1, type=int, 
                                       help="Number of users per setup")
generate_dashboard_config.add_argument('--output-dir', default="./dashboard_configs", 
                                       help="Output directory to generate configs")
generate_dashboard_config.add_argument('--master-ip', type=str, default="::1", required=False, 
                                   help="Master IP address")

# =================================================================================================

args = parser.parse_args()

# =================================================================================================
# Commands functions
# =================================================================================================

def get_systems_list(include_x=False):
    if args.system == 'all':
        systems = [system for system in ftdi_mapping.keys() if (system != 'X' or include_x)]
    else:
        systems = [args.system]
    return systems

# =================================================================================================

def flash():
    for system in get_systems_list():
        ftdi_path = ftdi_mapping[system]
        print("\n==> Flashing system ", system, f" with ftdi location {ftdi_path}\n")
        with tempfile.TemporaryDirectory() as tmpdirname:
            storage_path = os.path.join(tmpdirname, 'storge.img')
            subprocess.run([
                'artiq_mkfs',
                '-s', 'ip', ip_mapping[system],
                storage_path
            ])
            cmd = [
                'artiq_flash', '-t', 'kasli', 
                '-d', args.directory,
                '-f', storage_path, 
                'erase', 'gateware', 'bootloader', 'firmware', 'storage', 'start'
            ]
            if ftdi_path is not None:
                cmd = [cmd[0], '-I', f'ftdi_location {ftdi_path}'] + cmd[1:]
            print(cmd)
            subprocess.run(cmd)

# =================================================================================================

def restart():
    for system in get_systems_list():
        print("\n==> Restarting system ", system, f" with ftdi location {ftdi_mapping[system]}\n")
        ftdi_path = ftdi_mapping[system]
        cmd = [
            'artiq_flash', '-t', 'kasli',
            'start'
        ]
        if ftdi_path is not None:
            cmd = [cmd[0], '-I', f'ftdi_location {ftdi_path}'] + cmd[1:]
        subprocess.run(cmd)

# =================================================================================================

def serial():
    system = args.system
    print(f"\n==> Serial port for system {system} under {serial_mapping[system]}\n")
    print("\nTo exit press Ctrl + C\n")
    subprocess.run(['flterm', serial_mapping[system]])

# =================================================================================================

def ddb():
    for system in get_systems_list(include_x=True):
        scope_ip = scope_ip_mapping[system]
        scope_ctl_port = scope_controller_ports[system]
        scope_ctl_host = args.ctl_host

        with open(os.path.join(experiments_path, f"device_db_{system.lower()}.py"), 'w') as f:
            f.write(device_db_template.format(
                core_ip=ip_mapping[system],
                system=system,
                ctl_host=args.ctl_host,
                corelog_ctl_port=corelog_controller_ports[system],
                moninj_proxy_port=moninj_proxy_ports[system],
                moninj_ctl_port=moninj_controller_ports[system]
            ))
            if scope_ip is not None and scope_ctl_port is not None:
                f.write(scope_template.format(
                    ctl_host=scope_ctl_host,
                    scope_ctl_port=scope_ctl_port,
                    scope_ip=scope_ip))

# =================================================================================================

def update_master_scripts():
    os.makedirs(args.output, exist_ok=True)
    for system in get_systems_list():
        master_cmd = [
            # sys.executable,
            # "-u", "-m", 
            # "artiq.frontend.artiq_master",
            "artiq_master",
            "--device-db", f"device_db_{system.lower()}.py",
            "--bind", "'*'",
            "--port-notify", str(master_notify_ports[system]),
            "--port-control", str(master_control_ports[system]),
            "--port-logging", str(master_logging_ports[system]),
            "--port-broadcast", str(master_broadcast_ports[system]),
            "--name", f"\"System {system}\"",
        ]
        ctlmgr_cmd = [
            # sys.executable,
            # "-m", 
            # "artiq_comtools.artiq_ctlmgr",
            "artiq_ctlmgr",
            "--server", args.master_ip,
            "--port-notify", str(master_notify_ports[system]),
            "--port-logging", str(master_logging_ports[system]),
            "--port-control", str(ctlmgr_control_ports[system]),
        ]

        script_path = os.path.join(args.output, f'run_session_{system.lower()}')
        system_dir_path = os.path.abspath(
            os.path.join(args.target_dir, f"system_{system.lower()}"))

        with open(script_path, 'w') as f:
            f.write(f"#!/bin/bash\n\n")
            f.write(f"cd {system_dir_path}\n\n")
            f.write(" ".join(master_cmd) + " &\n\n")
            f.write("sleep 5\n\n")
            f.write(" ".join(ctlmgr_cmd) + "\n")

        st = os.stat(script_path)
        os.chmod(script_path, st.st_mode | stat.S_IEXEC)

# =================================================================================================

def start_session():
    assert args.system in ['A', 'B', 'C', 'D', 'E', 'F'], \
        "Invalid system, only A-F are allowed, one at a time"

    master_cmd = [
        sys.executable, 
        "-u", "-m", 
        "artiq.frontend.artiq_master",
        "--device-db", f"device_db_{args.system.lower()}.py",
        "--bind", "*",
        "--port-notify", str(master_notify_ports[args.system]),
        "--port-control", str(master_control_ports[args.system]),
        "--port-logging", str(master_logging_ports[args.system]),
        "--port-broadcast", str(master_broadcast_ports[args.system]),
        "--name", f"\"System {args.system}\"",
    ]
    ctlmgr_cmd = [
        sys.executable,
        "-m", 
        "artiq_comtools.artiq_ctlmgr",
        "--server", args.master_ip,
        "--port-notify", str(master_notify_ports[args.system]),
        "--port-logging", str(master_logging_ports[args.system]),
        "--port-control", str(ctlmgr_control_ports[args.system]),
    ]

    with subprocess.Popen(master_cmd,
                          cwd=experiments_path,
                          stdout=subprocess.PIPE, universal_newlines=True,
                          bufsize=1) as master:
        master_ready = False
        for line in iter(master.stdout.readline, ""):
            sys.stdout.write(line)
            if line.rstrip() == "ARTIQ master is now ready.":
                master_ready = True
                break
        if master_ready:
            with subprocess.Popen(ctlmgr_cmd):
                for line in iter(master.stdout.readline, ""):
                    sys.stdout.write(line)
        else:
            print("Master failed to start, exiting.")

# =================================================================================================

def dashboard():
    assert args.system in ['A', 'B', 'C', 'D', 'E', 'F'], \
        "Invalid system, only A-F are allowed, one at a time"

    dashboard_cmd = [
        sys.executable,
        "-m",
        "artiq.frontend.artiq_dashboard",
        "--server", args.master_ip,
        "--port-notify", str(master_notify_ports[args.system]),
        "--port-control", str(master_control_ports[args.system]),
        "--port-broadcast", str(master_broadcast_ports[args.system]),
    ]
    with subprocess.Popen(dashboard_cmd):
        pass

# =================================================================================================

def deploy():
    target_dir = args.target_dir
    users = args.users
    system = args.system
    user = args.user
    overwrite_system = args.overwrite_system
    overwirte_user = args.overwrite_user
    
    user = args.user
    
    def make_user_dir(system, user_i, overwrite):
        system_dir = os.path.join(target_dir, f"system_{system.lower()}")
        user_dir = os.path.join(system_dir, "repository", f"user_{user_i}")
        if not os.path.exists(user_dir):
            os.makedirs(user_dir)
        elif overwrite:
            shutil.rmtree(user_dir)
            os.makedirs(user_dir)
        else:
            print(f"Skipping creation of directory for system {system}, user {user_i}")
            return
        
        # Copy experiments
        for experiment_path in glob.glob(os.path.join(experiments_path, 'repository', '*.py')):
            experiment = os.path.basename(experiment_path)
            if experiment == "user.py":
                continue
            target_path = os.path.join(user_dir, f"user{user_i}_{experiment}")
            shutil.copy(
                experiment_path, 
                target_path)
            os.chmod(target_path, 0o664)
        
        # Generate user.py file
        user_file_path = os.path.join(user_dir, "user.py")
        with open(user_file_path, 'w') as user_file:
            user_file.write("# This file defines your user ID. DO NOT EDIT!\n")
            user_file.write(f"user_id = {user_i}\n")
        os.chmod(user_file_path, 0o664)

    def make_system_dir(system, overwirte):
        system_dir = os.path.join(target_dir, f"system_{system.lower()}")
        if not os.path.exists(system_dir):
            os.makedirs(system_dir)
        elif overwirte:
            shutil.rmtree(system_dir)
            os.makedirs(system_dir)
        else:
            raise RuntimeError(
                f"System {system} directory already exists, use --overwrite-system to recreate")
    
        target_ddb_path = os.path.join(system_dir, "device_db.py")
        shutil.copy(
            os.path.join(experiments_path, f"device_db_{system.lower()}.py"), 
            target_ddb_path)
        os.chmod(target_ddb_path, 0o644)

        # At this point user directories never exist
        for user_i in range(users):
            make_user_dir(system, user_i, False)

    # Make sure target dir exists
    os.makedirs(target_dir, exist_ok=True)

    # Mode for resetting user directory
    if user is not None:
        make_user_dir(system, user, overwirte_user)
    # Mode for creating system directories
    else:
        for system in get_systems_list():
            make_system_dir(system, overwrite_system)

# =================================================================================================

def generate_dashboard_config():
    applet_path = args.applet_path
    users = args.users
    master_ip = args.master_ip

    os.makedirs(args.output_dir, exist_ok=True)

    for system in get_systems_list():
        applets = []
        config = pyon.load_file(
            os.path.join(os.path.dirname(__file__), "dashboard_config.pyon"))
        applet_template = config['AppletsCCBDock']['applets'][0]
        for user_id in range(users):
            applets.append((
                'applet',
                user_id,
                False,
                f'User {user_id} Scope View',
                {
                    'command': f'python {applet_path} scope_{user_id}',
                    'ty': 'command'
                },
                applet_template[5]
            ))
        config['AppletsCCBDock']['applets'] = applets
        output_path = os.path.join(
            args.output_dir, f"dashboard_{master_ip}_{master_notify_ports[system]}.pyon")
        pyon.store_file(output_path, config)

# =================================================================================================
# Entrypoint function
# =================================================================================================

def main():
    if args.command == 'flash':    
        flash()
    elif args.command == 'restart':
        restart()
    elif args.command == 'serial':
        serial()
    elif args.command == "ddb":
        ddb()
    elif args.command == "update-scripts":
        update_master_scripts()
    elif args.command == "session":
        # start_session()
        print("Session command was disabled due to faulty implementation")
        exit(1)
    elif args.command == "dashboard":
        dashboard()
    elif args.command == "deploy":
        deploy()
        print("\nRemeber to update session scripts by running update-scripts command.\n")
    elif args.command == "generate-dashboard-config":
        generate_dashboard_config()
    else:
        print("Invalid command")
        exit(1)

if __name__ == "__main__":
    main()
