#!/usr/bin/env python

import subprocess
import argparse
import os
import tempfile
from setups import ftdi_mapping, ip_mapping


serial_mapping = {}

for system, ftdi_path in ftdi_mapping.items():
    if ftdi_path is None:
        serial_mapping[system] = "/dev/serial/by-id/usb-FTDI_Quad_RS232-HS-if02-port0"
        continue
    _, path = ftdi_path.split(':')
    path = path.replace(',', '.')
    serial_mapping[system] = f"/dev/serial/by-path/pci-0000:00:14.0-usb-0:{path}:1.2-port0"


# Create a subparser with command "flash"
parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(dest='command')

flash_parser = subparsers.add_parser('flash')
default_firmware_directory = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'firmware', 'qce24')
flash_parser.add_argument('--directory', '-d', type=str, default=default_firmware_directory, help="firmware directory")
flash_parser.add_argument('--system', '-s', type=str, required=True, help="which system to flash (A or B or .. F or X or 'all' for all)")

restart_parser = subparsers.add_parser('restart')
restart_parser.add_argument('--system', '-s', type=str, required=True, help="which system to restart (A or B or .. F or X or 'all' for all)")

serial_parser = subparsers.add_parser('serial')
serial_parser.add_argument('--system', '-s', type=str, required=True, help="which system to get serial from (A or B or .. F or X)")

device_db_parser = subparsers.add_parser('ddb')
device_db_parser.add_argument('--system', '-s', type=str, required=True, help="which system to restart (A or B or .. F or X or 'all' for all)")

args = parser.parse_args()

if args.command == 'flash':    
    systems = []
    if args.system == 'all':
        systems = ftdi_mapping.keys().remove('X')
        ips = [ip_mapping[system] for system in systems]
    else:
        systems = [args.system]
        ips = [ip_mapping[args.system]]

    for system, ip in zip(systems, ips):
        ftdi_path = ftdi_mapping[system]
        print("\n==> Flashing system ", system, f" with ftdi location {ftdi_path}\n")
        with tempfile.TemporaryDirectory() as tmpdirname:
            storage_path = os.path.join(tmpdirname, 'storge.img')
            subprocess.run([
                'artiq_mkfs',
                '-s', 'ip', ip,
                storage_path
            ])
            cmd = [
                'artiq_flash', '-t', 'kasli', 
                '-d', args.directory,
                '-f', storage_path, 
                'erase', 'gateware', 'bootloader', 'firmware', 'storage', 'start'
            ]
            if ftdi_path is not None:
                cmd = [cmd[0], '-I', f'ftdi_location {ftdi_path}'] + cmd[1:]
            print(cmd)
            subprocess.run(cmd)

elif args.command == 'restart':
    systems = []
    if args.system == 'all':
        systems = ftdi_mapping.keys().remove('X')
    else:
        systems = [args.system]

    for system in systems:
        print("\n==> Restarting system ", system, f" with ftdi location {ftdi_mapping[system]}\n")
        ftdi_path = ftdi_mapping[system]
        cmd = [
            'artiq_flash', '-t', 'kasli',
            'start'
        ]
        if ftdi_path is not None:
            cmd = [cmd[0], '-I', f'ftdi_location {ftdi_path}'] + cmd[1:]
        subprocess.run(cmd)

elif args.command == 'serial':
    system = args.system
    print(f"\n==> Serial port for system {system} under {serial_mapping[system]}\n")
    print("\nTo exit press Ctrl + C\n")
    subprocess.run(['flterm', serial_mapping[system]])

elif args.command == "ddb":
    systems = []
    if args.system == 'all':
        systems = ftdi_mapping.keys()
        ips = [ip_mapping[system] for system in systems]
    else:
        systems = [args.system]
        ips = [ip_mapping[args.system]]

    expeirments_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'experiments')
    ddb_template_path = os.path.join(expeirments_path, 'ddb_tmp.py')
    
    with open(ddb_template_path, 'r') as f:
        ddb_template = f.read()
    for system, ip in zip(systems, ips):
        with open(os.path.join(expeirments_path, f"device_db_{system.lower()}.py"), 'w') as f:
            f.write(ddb_template.replace("%%core_ip%%", ip).replace("%%system%%", system))


else:
    print("Invalid command")
    exit(1)
