#!/bin/bash

artiq_master --device-db device_db_e.py --bind * --port-notify 3254 --port-control 3265 --port-logging 1064 --port-broadcast 1164 --name "System E" &

sleep 5

artiq_ctlmgr --server 172.31.91.201 --port-notify 3254 --port-logging 1064 --port-control 3275
